require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SetlistSongsController do

  # This should return the minimal set of attributes required to create a valid
  # SetlistSong. As you add validations to SetlistSong, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all setlist_songs as @setlist_songs" do
      setlist_song = SetlistSong.create! valid_attributes
      get :index
      assigns(:setlist_songs).should eq([setlist_song])
    end
  end

  describe "GET show" do
    it "assigns the requested setlist_song as @setlist_song" do
      setlist_song = SetlistSong.create! valid_attributes
      get :show, :id => setlist_song.id.to_s
      assigns(:setlist_song).should eq(setlist_song)
    end
  end

  describe "GET new" do
    it "assigns a new setlist_song as @setlist_song" do
      get :new
      assigns(:setlist_song).should be_a_new(SetlistSong)
    end
  end

  describe "GET edit" do
    it "assigns the requested setlist_song as @setlist_song" do
      setlist_song = SetlistSong.create! valid_attributes
      get :edit, :id => setlist_song.id.to_s
      assigns(:setlist_song).should eq(setlist_song)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SetlistSong" do
        expect {
          post :create, :setlist_song => valid_attributes
        }.to change(SetlistSong, :count).by(1)
      end

      it "assigns a newly created setlist_song as @setlist_song" do
        post :create, :setlist_song => valid_attributes
        assigns(:setlist_song).should be_a(SetlistSong)
        assigns(:setlist_song).should be_persisted
      end

      it "redirects to the created setlist_song" do
        post :create, :setlist_song => valid_attributes
        response.should redirect_to(SetlistSong.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved setlist_song as @setlist_song" do
        # Trigger the behavior that occurs when invalid params are submitted
        SetlistSong.any_instance.stub(:save).and_return(false)
        post :create, :setlist_song => {}
        assigns(:setlist_song).should be_a_new(SetlistSong)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SetlistSong.any_instance.stub(:save).and_return(false)
        post :create, :setlist_song => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested setlist_song" do
        setlist_song = SetlistSong.create! valid_attributes
        # Assuming there are no other setlist_songs in the database, this
        # specifies that the SetlistSong created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SetlistSong.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => setlist_song.id, :setlist_song => {'these' => 'params'}
      end

      it "assigns the requested setlist_song as @setlist_song" do
        setlist_song = SetlistSong.create! valid_attributes
        put :update, :id => setlist_song.id, :setlist_song => valid_attributes
        assigns(:setlist_song).should eq(setlist_song)
      end

      it "redirects to the setlist_song" do
        setlist_song = SetlistSong.create! valid_attributes
        put :update, :id => setlist_song.id, :setlist_song => valid_attributes
        response.should redirect_to(setlist_song)
      end
    end

    describe "with invalid params" do
      it "assigns the setlist_song as @setlist_song" do
        setlist_song = SetlistSong.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SetlistSong.any_instance.stub(:save).and_return(false)
        put :update, :id => setlist_song.id.to_s, :setlist_song => {}
        assigns(:setlist_song).should eq(setlist_song)
      end

      it "re-renders the 'edit' template" do
        setlist_song = SetlistSong.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SetlistSong.any_instance.stub(:save).and_return(false)
        put :update, :id => setlist_song.id.to_s, :setlist_song => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested setlist_song" do
      setlist_song = SetlistSong.create! valid_attributes
      expect {
        delete :destroy, :id => setlist_song.id.to_s
      }.to change(SetlistSong, :count).by(-1)
    end

    it "redirects to the setlist_songs list" do
      setlist_song = SetlistSong.create! valid_attributes
      delete :destroy, :id => setlist_song.id.to_s
      response.should redirect_to(setlist_songs_url)
    end
  end

end
